name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: cd Server && dotnet restore && cd .. && cd Shared && dotnet restore && cd .. && cd Client && dotnet restore && cd ..
    - name: Build
      run: cd Server && dotnet build --configuration Release --no-restore && cd ..
    - name: Test
      run: cd Server && dotnet test --no-restore --verbosity normal && cd ..
